// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhU1vbTEVhtt6TbzY1n9Lnzf765_JSDro',
    appId: '1:250826396400:web:638e379c8c6aeba488e835',
    messagingSenderId: '250826396400',
    projectId: 'carbecho-80ea4',
    authDomain: 'carbecho-80ea4.firebaseapp.com',
    storageBucket: 'carbecho-80ea4.appspot.com',
    measurementId: 'G-72TXY49ZVD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYjH1zs7HatsavizcUhwRIPz7KJqjyWTk',
    appId: '1:250826396400:android:fbc0f19acc797dfb88e835',
    messagingSenderId: '250826396400',
    projectId: 'carbecho-80ea4',
    storageBucket: 'carbecho-80ea4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDNn-1F1f-AhPtDlX5htufsAtLTWVROx0',
    appId: '1:250826396400:ios:0f73180398852bd988e835',
    messagingSenderId: '250826396400',
    projectId: 'carbecho-80ea4',
    storageBucket: 'carbecho-80ea4.appspot.com',
    iosBundleId: 'com.example.carbecho',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDNn-1F1f-AhPtDlX5htufsAtLTWVROx0',
    appId: '1:250826396400:ios:e6532447dcd0831788e835',
    messagingSenderId: '250826396400',
    projectId: 'carbecho-80ea4',
    storageBucket: 'carbecho-80ea4.appspot.com',
    iosBundleId: 'com.example.carbecho.RunnerTests',
  );
}
